### ISSUE TITLE
[makefile] add awscli dependency install to makefile

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#1]

**Comment by eswarasai** [comment]
@pelsasser -- This can be closed right? Moreover, I think we can remove the AWS deploy from `makefile` as we have automated deployment in place already

**Comment by pelsasser** [comment]
would prefer to leave them in, even if it is just for the dev.website deployment, it is sometimes nice to have finer grain control for testing things than having to commit them.
