### ISSUE TITLE
[about] punchlists of item from Aure for /about

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#108]
- [x] on the header, line height 1.2
- [x] on the h2s line height 1.1
- [x] on the h2s font weight 500
- [x] in general on mobile the h1 at the top needs more margin at the top
- [x] it's bumping right into the logo
- [x] those h1s seem huge on desktop...
- [ ] h2s are inconsistent weights on this page
- [x] update timelines from update files that are available in assets [mobile](https://github.com/MARKETProtocol/assets/blob/master/MockUps/MARKET_Protocol-timeline-mobile.sketch) and [desktop](https://github.com/MARKETProtocol/assets/blob/master/MockUps/MARKET_Protocol-website.sketch)

**Comment by nitinrgupta** [comment]
👍 Will knockout these changes.
