### ISSUE TITLE
[partners] punch list from aure for /partners page 

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#109]
- [ ] not loving the placement of the illustration at the top, should be more centered horizontally in that whitespace
- [ ] h1 seems smaller here than on the about
- [ ] white boxes on partners should all be squares
- [ ] some of those logos are huge
- [ ] at the bottom, the minds behind is a heavier weight than the email us on other pages
- [ ] noticed we got rid of one module down there, from 3 across to 2
- [ ] they're a bit too wide now but not big deal for now
- [ ] that illustration's all messed up, need to clean it up on my end and provide a replacement. but placement of it can be fixed now
- [ ] the background behind the top bar should be slightly transparent so you can see the parts of the illustrations that are underneath it

**Comment by nitinrgupta** [comment]
Will get this knocked out along with my `/about` page changes
