### ISSUE TITLE
'The minds behind MARKET Protocol' link should not trigger a page reload

### ISSUE THREAD

**Issue by arun1595** [MARKETProtocol/website#122]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a developer, I want any internal page links on the app to trigger a page reload.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
Clicking on 'The minds behind MARKET Protocol' button causes a page reload.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
'The minds behind MARKET Protocol' button should not a page reload 

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Go to https://marketprotocol.io/partners/
- Click on 'The minds behind MARKET Protocol' button at the bottom

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.001 ETH (0.69 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/MARKETProtocol/website/122/742).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
