### ISSUE TITLE
[Footer] add YouTube social media icon

### ISSUE THREAD

**Issue by lakikentaki** [MARKETProtocol/website#124]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

-->

### User Story

As a website visitor, I want to be able to access social media channels so that I can learn more about the project.

### Why Is this Needed?

*Summary*: So people can easily find our youtube channel

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior

No YoutTube Link

### Expected Behavior

A YouTube Link

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

- [ ] Add a YouTube icon (available in attachment) and hyperlink: https://www.youtube.com/c/MARKETProtocol
YouTube icon: 
![youtube](https://user-images.githubusercontent.com/39289842/40788293-4e9fb210-64b5-11e8-91e1-07467648dbc5.png)
![youtube](https://user-images.githubusercontent.com/39289842/40788572-0409891e-64b6-11e8-8b26-4a9cb70d9698.png)

**Comment by lakikentaki** [comment]
Update: The links are working in Chrome, but for some reason, they don't in my Firefox browser.

**Comment by pelsasser** [comment]
@lakikentaki - confirmed on firefox the links do not work. - separating the functionality issue and the youtube issue now.

**Comment by pelsasser** [comment]
#115 created for bug fix.
