### ISSUE TITLE
[General] Buttons across site do not work with firefox 

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#125]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story

I want to be able to use firefox and visit our site and have the buttons work

### Why Is this Needed?

*Summary*: Many people use firefox!

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
Using firefox, none of the buttons on the site that have <Links/> wrapped inside of them work.  

### Expected Behavior
All buttons link correctly.

### Reproduction
visit marketprotocol.io in firefox and click on any of the buttons in the footer - 

![image](https://user-images.githubusercontent.com/15096737/40791636-34b394f2-64b5-11e8-8379-dacb6c7d1ff6.png)

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:Sounds like we may have some malformed Javascript that works in chrome but not universally.

### Definition of Done
Fix all buttons across entire site.

**Comment by arun1595** [comment]
@pelsasser We can close this as the issue is fixed in https://github.com/MARKETProtocol/website/commit/4643cb4155c23b7360c6709e28e58d2bebc13717
