### ISSUE TITLE
Image issues with font on graphic 

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#13]
![image](https://user-images.githubusercontent.com/15096737/39132403-ff4d22d2-46ce-11e8-9d80-4c5855a6ad03.png)

There are some font issues here - let me know if this is from the mockup or some other issue and we can resolve @nitinrgupta

**Comment by nitinrgupta** [comment]
Oh! This is because I'm using SVGs. 

Will convert the text to shapes. Good catch 👍

**Comment by pelsasser** [comment]
fixed.
