### ISSUE TITLE
[Team] H1 in header not aligned with "Core Team"

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#130]
### User Story

As a user something feels off with wide widths and the team page 

### Why Is this Needed?

*Summary*: Alignment

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: @auregimon and @nitinrgupta to solve.

**Comment by nitinrgupta** [comment]
@pelsasser are you reffering to the below allignment? 
![screen_shot_2018-06-05_at_3_24_56_pm](https://user-images.githubusercontent.com/4952395/40969124-bfa92982-68d4-11e8-9dce-72181b14f5e6.png)

**Comment by pelsasser** [comment]
@nitinrgupta - @auregimon may be the best to respond here, but I think his concern was with 
![image](https://user-images.githubusercontent.com/15096737/40975271-9c3e9c7c-6887-11e8-88d1-5a74b030b4e1.png)

"The Team"
Compared to 
"Core Team"

**Comment by nitinrgupta** [comment]
Yea. I kinda agree. The margins on the entire team page are improper. Need to devise a solution for it.

**Comment by KennethAshley** [comment]
All it might take is to center the titles. What do you guys think?

![screencapture-localhost-3000-team-2018-07-02-21_04_27](https://user-images.githubusercontent.com/1138619/42193319-e6934484-7e3b-11e8-9c94-9dba9c21a612.png)

**Comment by eswarasai** [comment]
@KennethAshley -- Can you quickly create a PR for this one? Looks like this one's been long pending and a piece of cake for you. Thanks!

**Comment by KennethAshley** [comment]
Yea!
