### ISSUE TITLE
[Whitepaper] Update white paper with missing team and advisors from /team page

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#144]
### Why Is this Needed?
*Summary*: Consistency

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

### Current Behavior
/team and /whitepaper do not match.  We have added advisors and team members!

### Expected Behavior
All new people added to /whitepaper

### Definition of Done

- [ ] Match /team to /whitepaper for all new people
- [ ] Update / write test for all new code generated

**Comment by iamonuwa** [comment]
@pelsasser, I'll need bio information for Rob Behnke and Kevin Owocki

**Comment by pelsasser** [comment]
@lakikentaki - can you please facilitate the need bios for these two?

@iamonuwa - you can just stick some fake text in until we get them.

**Comment by iamonuwa** [comment]
Will do @pelsasser

**Comment by lakikentaki** [comment]
Kevin Owocki: 

Kevin Owocki is the founder of Gitcoin.co.  He is a software engineer interested in hacking, learning, and writing about the intersection of next-generation technologies, especially machine learning, computer vision, VR, AR, & plenoptic photography.  He has a BS in Computer Science, 10 years of engineering leadership experience in startups and Open Source Software.  He also is a community organizer in the Boulder Colorado Blockchain Tech Scene, helping many notable events planning, like ETHDenver with one of MARKET Protocol co-founders Phil Elsasser.

Rob Behnke: 

Rob Behnke is a 5-year cryptocurrency trader, token sale growth hacker, and entrepreneur currently living in San Francisco. His prior - The Brooklyn Salsa Company and the MicSwap iOS App have been featured in Forbes, Techcrunch and the New York Times. He is the founder of Token Agency - a premier, full-service marketing and strategy agency for the blockchain startup space that successfully launched and worked with multiple ICOs / Token Sales / Token Generation Events.

**Comment by iamonuwa** [comment]
@lakikentaki, I'll update this. Thank you
