### ISSUE TITLE
[Blog] Implement data fetching and interactions to existing /blog page

### ISSUE THREAD

**Issue by hbeckeri** [MARKETProtocol/website#146]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Adds functionality and to the existing /blog page.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:  Feature

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: Add data fetching for recent tweets and interactions with loading more blogs, and sign-up.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Implement data fetching for recent tweets
- [ ] Implement data fetching for more blogs
- [ ] Implement interaction with the sign up button
- [ ] Update tests as needed
- [ ] Add new tests for all newly generated code
- [ ] Interact with @MARKETProtocol/core and expect a few revisions

**Comment by ceresstation** [comment]
Hey @hbeckeri I think some of this may have been implemented at this point. Are you able to double check and update the issue accordingly?

**Comment by hbeckeri** [comment]
@ceresstation I've updated the issue

**Comment by pelsasser** [comment]
@ceresstation - going to close this and open specific issues on the specific tasks. 

@hbeckeri - thanks for your help here!
