### ISSUE TITLE
[Jobs] Issue with some widths and responsiveness

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#151]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
![image](https://user-images.githubusercontent.com/15096737/41502480-10d5be14-7178-11e8-9bcb-c0c3ef040ff6.png)

### Current Behavior
Screenshot taken at 1232

### Expected Behavior
All boxes are same size at all resolutions

### Reproduction
Looks like it happens with widths b/w 1200-1300

**Comment by iamonuwa** [comment]
@pelsasser can I work on this?

**Comment by pelsasser** [comment]
sure! thanks @iamonuwa!

**Comment by iamonuwa** [comment]
Awesome. Thank you
