### ISSUE TITLE
[Tag Manager] Install Google Tag Manager 

### ISSUE THREAD

**Issue by lakikentaki** [MARKETProtocol/website#154]
### User Story

As a Google Analytics admin, I want to be able to track conversions and tags using a tool called "Google Tag Manager" 

### Why Is this Needed?
*Summary*: This is needed for higher level performance on our social media. 

### Description
*Type*: Feature

### Current Behavior
The "Google Tag Manager" is not installed on our website. 

### Expected Behavior
The "Google Tag Manager" is installed on our website. 

### Solution
*Summary*:

To install "Google Tag Manager" please follow these steps (I will also provide a screenshot in the Additional information: 

- [ ] Copy the code below and paste it onto every page of your website.
- [ ] Paste this code as high in the < head > of the page as possible: 

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-TN3ZVBH');</script>

- [ ] Additionally, paste this code immediately after the opening < body > tag: 

noscript<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TN3ZVBH"
height="0" width="0" style="display:none;visibility:hidden"></iframe></nos cript>

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

The work is considered done once all pages on the website have the code above included in their < head > and < body >

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
Since Github hides stuff when they are put in <> please look at the screenshot as a code reference to make sure it's good or send me an email - lazar@marketprotocol.io and I'll forward it to you as is. 
![google tag manager](https://user-images.githubusercontent.com/39289842/41512911-856339e2-7258-11e8-93e2-6dfae14e1a9c.PNG)

**Comment by pelsasser** [comment]
@eswarasai - do you mind taking this on, I know your the one that set up the GA tags to begin with.  Marketing firm needs some help in getting this running. 

Some resources - 
https://developers.google.com/tag-manager/quickstart
https://www.npmjs.com/package/react-google-tag-manager

**Comment by lakikentaki** [comment]
@eswarasai we can also do the same for https://dev.website.marketprotocol.io

Head: 
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WDMKD33');</script>

Body: 
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WDMKD33"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by eswarasai** [comment]
@lakikentaki -- Let me know if I can close this issue once you've tested the changes. Thanks!

**Comment by lakikentaki** [comment]
@eswarasai I will sync back with Jim to see how exactly can we test this out and confirm when done.
