### ISSUE TITLE
[General] site changes from feedback of Marketing firm

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#157]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

Some feedback that may help us convert visitors 

### Solution

- [ ] Add Subscribe Button underneath hero text
- [ ] Fix Navbar `Whitepaper` link to direct immediately to English whitepaper if clicked instead of people using dropdown
- [ ] Add `Join Our Email List` to floating telegram pop up (only on desktop resolutions, leave mobile as is)
- [ ] Make the navbar static (frozen to top of page even when scrolling)
- [ ] Remove `Subscribe` from navbar and replace with `Partners`
- [ ] Add Text to /team page to make sure people realize the images are clickable for bio 
- [ ] Add text below (in comment) to subscribe modal
- [ ] Update or add any missing testing for these changes

**Comment by pelsasser** [comment]
cc @KennethAshley - LMK if you have questions on any of this.

**Comment by KennethAshley** [comment]
@pelsasser Looks pretty straightforward. I should be able to start on this today. Thanks!

**Comment by pelsasser** [comment]
Can we also add to the Subscribe modal 

> You can change your mind at any time by clicking the unsubscribe link in the footer of any email you receive from us, or by contacting us at info@marketprotocol.io. We will treat your information with respect. For more information about our privacy practices please visit our website. By clicking below, you agree that we may process your information in accordance with these terms.

**Comment by pelsasser** [comment]
thanks @KennethAshley and @nitinrgupta for all the help and coordination here!
