### ISSUE TITLE
Center buttons below text 

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#16]
![image](https://user-images.githubusercontent.com/15096737/39134367-b2ac9e76-46d3-11e8-9184-31df56f7ab68.png)

![image](https://user-images.githubusercontent.com/15096737/39134419-cedcb428-46d3-11e8-8b4d-1cc8c51a4683.png)

example from mock - 

![image](https://user-images.githubusercontent.com/15096737/39134448-e3222274-46d3-11e8-9d3c-340f1d9102c3.png)

**Comment by nitinrgupta** [comment]
Centering the buttons below the texts don't feel right @pelsasser because the texts are left aligned.
That's why I've left aligned the buttons as well to make to feel natural.

**Comment by pelsasser** [comment]
@nitinrgupta okay - so you don't like how it looks in the mock? I like the stacked buttons being the same width essentially matching that to the column width of the text.  Have you tried something like that? still seems off?

**Comment by nitinrgupta** [comment]
In the mockups it looks fine. But if in the implementation, we have to consider the cases where the width of the screen would be huge, like in a 15" screen etc which might not look good. Have a look at the current implementation and let me know if its fine. 
I've modified in such a way that the buttons will take full width in mobile resolutions.

**Comment by pelsasser** [comment]
okay - for the sake of time to market which is a big concern right and the fact that I do like your implementation, lets close this and move on for now!  Thanks for the feedback.
