### ISSUE TITLE
[Blog] Recent Tweets Widget

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#161]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### Description

*Type*:  Feature

### Current Behavior
UI implemented with no backend hook up to fetch and display recent tweets. 

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: Implement solution to fetch and display recent tweets from our [twitter](https://twitter.com/MarketProtocol)

### Definition of Done

- [ ] Tweets are fetched and displayed in the /blog page
- [ ] Tests written for all new code generated

See http://dev.website.marketprotocol.io/blog/ for the currently deployed blog

**Comment by pelsasser** [comment]
@KennethAshley - working on this one.

**Comment by pelsasser** [comment]
@KennethAshley - any status update on this one? thanks!

**Comment by KennethAshley** [comment]
Yea! Gonna hop on this is today!

**Comment by KennethAshley** [comment]
@pelsasser @eswarasai here is a worked around as suggested. Its a twitter embed but i think it looks nice. What do you guys think?

![image](https://user-images.githubusercontent.com/1138619/41874990-82f02da6-7897-11e8-82ba-42e5ba0b5811.png)
