### ISSUE TITLE
[Blog] Link to post

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#162]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.
### User Story

As a reader of the blog I want to be easily able to click on a post and read it.

### Why Is this Needed?

*Summary*:UX

### Description

*Type*: Feature
Edit /blog to allow a click anywhere on the blog tile to open the post.  (Except for the social icons)

### Current Behavior
Small link to continue reading

### Expected Behavior
Click anywhere on post tile to continue reading

### Reproduction
see http://dev.website.marketprotocol.io/blog/

### Definition of Done
- [ ] Create link to blog post from tile
- [ ] Add / update any tests for all new code generated

**Comment by KennethAshley** [comment]
Is this already completed?

**Comment by pelsasser** [comment]
Looks like it!
