### ISSUE TITLE
[Blog] Migrate existing content from medium into CMS

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#176]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story

As a user I want to be able to find all of the awesome content created by MARKET Protocol on the internal blog 

### Why Is this Needed?

*Summary*: Migrating primary source of content to our internal blog 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
Content all on medium 

### Expected Behavior
Content all on our site

### Definition of Done
1. For every medium post located [here](https://medium.com/market-protocol/archive) (sort by oldest) create a new internal blog post with the same images, headers, quotes, etc. 
1.  These can be created using the CMS or by using raw markdown
1. Include date published (use the medium published date), author, etc.
1. Create new categories that generally seem reasonable for the posts (these may need to be modded)

### Additional Information
All of this currently is attached the `blog` branch

**Comment by pelsasser** [comment]
@arun1595 please let me know if you have any questions

**Comment by pelsasser** [comment]
@arun1595 - how is the progress, any questions?

**Comment by arun1595** [comment]
@pelsasser I have submitted a [PR](https://github.com/MARKETProtocol/website/pull/180), check it out when you get a chance!
