### ISSUE TITLE
[About] Add button to Engineering Weekly section to add to Google Calendar

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#181]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story
As a user, I want a quick way to join `Engineering Weekly` each week.

### Why Is this Needed?
*Summary*: Easy way for people to join in 

### Description
*Type*: Feature

### Solution
*Summary*: Create a google calendar link that includes the zoom call link 

Example from https://www.originprotocol.com/en/developers
![image](https://user-images.githubusercontent.com/15096737/42233402-afeea50e-7eae-11e8-8985-0ed6261d9d26.png)

### Definition of Done
Add button for Google calendar link
Add / update all testing

**Comment by KennethAshley** [comment]
Just for clarification we want to add an "Add to Calendar" on the about page in the "Engineering Weekly" section?

**Comment by pelsasser** [comment]
yup
