### ISSUE TITLE
[Press] Add the 4 latest press releases about partnership with Kleros to website press page  

### ISSUE THREAD

**Issue by lakikentaki** [MARKETProtocol/website#187]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### Why Is this Needed?

_Summary:_ Our recent partnership with Kleros has been featured in 3 media outlets and we would like for them to be available to our website visitors in the future. 

### Description

_Type:_ Feature

### Current Behavior

Press releases and associated captions aren't available on our website press page.

### Expected Behavior

Press releases and associated captions are available on our website press page.

### Solution

_Summary:_ We want the press releases posted with associated captions, with the transparent logo of the PR publication. The logos are attached below.

- [ ]   Follow the same design style as on our [current press page](https://marketprotocol.io/press/) and consult our [branding guidelines](https://github.com/MARKETProtocol/assets/blob/master/Branding/MARKET_Protocol-Style-Guide.pdf)
- [ ]   Keep the same ratio between logo and captions as previous press page content

### Definition of Done

- [ ]   All press releases are posted and the hyperlink to each of them is attached to the publication logo and the "read more" button
- [ ]   Captions are copied from the press release in length that matches the proportion of other press page content that was previously posted

### Additional Information

Press releases: 
1. https://www.bankingtech.com/2018/07/kleros-teams-with-market-protocol-for-decentralised-derivatives-trading/
2. http://www.chain-finance.com/2018/07/06/decentralized-derivatives-trading-through-blockchain/
3. http://www.mondovisione.com/media-and-resources/news/kleros-partners-with-market-protocol-for-decentralized-derivatives-trading-the/
4. https://www.crowdfundinsider.com/2018/07/135963-dispute-layer-kleros-partners-with-derivative-platform-market-protocol/

Publisher's logos:
1.  Fintech Futures
![fintech logo 2](https://user-images.githubusercontent.com/39289842/42412436-f88d051e-81d1-11e8-89ca-1f404ab1519b.png)

2. Chain Finance
![chain-finance-draft-1](https://user-images.githubusercontent.com/39289842/42412443-0a7c20b6-81d2-11e8-83fe-059879287668.png)

3. Mondovisione
![mondo-visione](https://user-images.githubusercontent.com/39289842/42412450-246e59da-81d2-11e8-9432-2b0da9dec53e.png)

4. Crowdfund Insider 
![crowdfund-insider-logo copy](https://user-images.githubusercontent.com/39289842/42412722-4679f3ea-81d7-11e8-9b40-48d4d0c53bfe.png)

**Comment by arun1595** [comment]
@lakikentaki I'm on it.
