### ISSUE TITLE
[team] Add new team members to team page

### ISSUE THREAD

**Issue by travisdmathis** [MARKETProtocol/website#191]
### Why Is this Needed?

We have added two new team members.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:  Feature

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
Add the following team members to the team page.:

Travis Mathis
-  linkedin: https://www.linkedin.com/in/travis-mathis-43443b16/, 
-  github: travisdmathis, 
-  email: travis@marketprotocol.io 
![travism](https://user-images.githubusercontent.com/1335198/42471546-122e99a4-838c-11e8-89df-0cae7c0a837e.png)

Nitin Gupta
-  github: nitinrgupta, 
- email: nitin@marketprotocol.io, 
-  linkedin: ask before starting

 
### Definition of Done
- [ ] Travis Mathis added to team page
- [ ] Nitin Gupta added to team page

**Comment by iamonuwa** [comment]
@pelsasser @travisdmathis  am available to pick this task

**Comment by pelsasser** [comment]
@iamonuwa - thanks! @nitinrgupta can you provide an headshot?

**Comment by nitinrgupta** [comment]
@iamonuwa here you go
![cki_5278](https://user-images.githubusercontent.com/4952395/42508573-9d202322-8466-11e8-92ff-a73d534c3771.jpg)

**Comment by iamonuwa** [comment]
@pelsasser @travisdmathis @nitinrgupta please can I get bio about this profile?

**Comment by travisdmathis** [comment]
Bio:
Travis Mathis is a software developer from Burlington, VT.  He's comes from a web 2.0 development background and has owned and operated several startups. He has over 10 years experience in software engineering and has worked on numerous projects as a contractor, freelancer, and team member.

**Comment by iamonuwa** [comment]
Thanks guys

**Comment by pelsasser** [comment]
@iamonuwa - how is this coming?

**Comment by iamonuwa** [comment]
On it @pelsasser
