### ISSUE TITLE
[Blog] remove links to medium 

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#207]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story
As a user of the CMS, I want to post to our blog first and THEN cross post to medium, so the medium link will not exist at the time of creating the blog post.

### Why Is this Needed?
*Summary*: work flow.

### Description
*Type*: Bug

### Solution

*Summary*: Easiest solution is just to fully remove the medium links from our blog posts and the CMS entries.

### Definition of Done
- edit public/adming/config.yml to remove need for medium link
- updated blog and posts to remove the medium link
- fix / update any tests that may need updating.

**Comment by pelsasser** [comment]
@KennethAshley - any interest in picking this one up?

**Comment by KennethAshley** [comment]
@pelsasser For sure. I'll get this done.

**Comment by KennethAshley** [comment]
@pelsasser could you pinpoint where exactly on the blog we are linking to medium? All i see is medium in the 'follow us' section of the sidebar.

**Comment by pelsasser** [comment]
@KennethAshley - do a quick search for `medium_link`

We can leave it in the blog posts that are already created, but need to remove it from everywhere else

public/admin/config.yml 
and
![image](https://user-images.githubusercontent.com/15096737/43199748-485d8fa8-8fd0-11e8-82d5-d1b2022ca5a1.png)
