### ISSUE TITLE
Bug: history is undefined on blog page

### ISSUE THREAD

**Issue by KennethAshley** [MARKETProtocol/website#210]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story
As a user i want to be able to click on blog post on the blog page

### Why Is this Needed?
To see the full blog content

### Current Behavior
Go to `/blog` and click on a preview. Nothing happens. Blahhhh

### Expected Behavior
I should be taken to a specific blog post when clicking on its preview.

### Solution
Include `history` in the props

### Definition of Done
I will be able to go to the blog post

**Comment by rojosnow** [comment]
@KennethAshley Hi! Any update on this issue?

**Comment by KennethAshley** [comment]
@rojosnow fixing this now!

**Comment by KennethAshley** [comment]
This seems to be fixed. http://dev.website.marketprotocol.io/blog/ seems to be working correctly.

**Comment by rojosnow** [comment]
@KennethAshley What about on production? I'm not sure which environment @pelsasser saw this one.

**Comment by eswarasai** [comment]
@KennethAshley -- I can still reproduce the issue on my end at http://dev.website.marketprotocol.io/blog/. Can you double check on incognito as well once?
