### ISSUE TITLE
[Jobs] Create a new job listing for the position of Community Growth Manager 

### ISSUE THREAD

**Issue by lakikentaki** [MARKETProtocol/website#215]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a website visitor, I want to be able to see the new job listing so that I can apply for it. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

The Community Growth Manager open position is not listed on our jobs page. 

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

The Community Growth Manager open position is listed on our jobs page. 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

The task is considered done once the open position for the Community Growth Manager is posted according to the previous [job listings](http://dev.website.marketprotocol.io/jobs#jobList) and associated description is hyperlinked properly. The job description is available in additional information. 

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

[Community Growth Manager.pdf](https://github.com/MARKETProtocol/website/files/2250035/Community.Growth.Manager.pdf)

**Comment by rojosnow** [comment]
@arun1595 How are you doing here? We'd like to get this posted asap! Thanks!

**Comment by nitinrgupta** [comment]
@arun1595 grabbing this in the interest of putting it out there quickly 

cc: @rojosnow

**Comment by rojosnow** [comment]
@nitinrgupta Thanks for getting on this!
