### ISSUE TITLE
[Blog] preview of blog posts don't render markdown correctly. 

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#233]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story
As a reader of the blog I would like the previews to look neat and readable. 

### Why Is this Needed?
*Summary*: draw people in to read more.

### Description
*Type*: Bug

### Current Behavior
See the preview in the below screenshot, the markdown renders into plain text and makes it look very odd!

![image](https://user-images.githubusercontent.com/15096737/44149009-bd190600-a057-11e8-9cc2-b54a1966382e.png)

### Expected Behavior
The markdown either is rendered correctly, or simply removed so we just have plain text in the preview

### Reproduction
see https://marketprotocol.io/blog/

### Solution
*Summary*: Fix issues with previews and mark down.

### Definition of Done
- [ ] issues resolved with previews
- [ ] all tests updated for any new code genereated / old code modified

**Comment by rojosnow** [comment]
ON HOLD. Move to the CMS repo.

**Comment by pelsasser** [comment]
closed to move to new repo - https://github.com/MARKETProtocol/cms/issues/2
