### ISSUE TITLE
[email] Change marketing email provider to SendGrid

### ISSUE THREAD

**Issue by rojosnow** [MARKETProtocol/website#255]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a marketer, I need the ability to use SendGrid as our marketing email provider since MailChimp has banned crypto companies.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happen)
*Summary*:
MailChimp has banned crypto companies from their platform.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

### Current Behavior
[comment]: # (Describe what actually happened.)
MailChimp is being used for marketing emails.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Migrate to SendGrid as our marketing email provider.

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
Replace MailChimp with SendGrid.

https://sendgrid.com/docs/for-developers/

@eswarasai is investigating the scope and complexity of the migration. More details will be provided.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- All current marketing email functionality has been migrated to SendGrid
- New tests are developed to support SendGrid
- All applicable tests pass

**Comment by pelsasser** [comment]
Currently we have to mailing lists on the site
1. General email newsletter
1. Token interest form / updates
