### ISSUE TITLE
[Become a Partner] Allow potential partners to email us 

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#26]
### User Story

The `Become A Partner` action should be turned around from us emailing someone to a potential partner emailing us.  For the time being this can be as simply as a `mailto:partnerships@marketprotocol.io` and eventually could be a form.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: We need more info and context from people who may want to partner with us

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

- [ ] add `mailto:partnerships@marketprotocol.io"
- [ ] change button design to suggest this action vs user entering email address
- [ ] we should include a auto populated subject and even some body text that helps direct the conversation (see [here](https://yoast.com/dev-blog/guide-mailto-links/) on how to implement)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
All items above completed

## Before you `start work`
If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

**Comment by perfectmak** [comment]
I think I should be able to do this quickly. What is the proposed subject and body text we can include? @pelsasser
