### ISSUE TITLE
[Main Hero Graphic] Increase resolution of .png

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#35]
### Description

Main hero graphic is a bit grainy on larger monitors

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: increase resolution of graphic

**Comment by nitinrgupta** [comment]
Will be updating the png image to svg real soon.

**Comment by pelsasser** [comment]
thanks @nitinrgupta !!
