### ISSUE TITLE
[General] Add link / button on main page to learn more about contributing

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#43]
### User Story

Potential contributors my find site and not early realize that we are extremely welcoming of new contributors

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: We want to continue to grow and foster our OSS development community

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: Design a nice way of adding some sort of information to direct people to https://docs.marketprotocol.io/#contributing

## Before you `start work`
If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

**Comment by vikaskyadav** [comment]
Either we can provide one more link in top navbar or in the footer menu. rest of the page discusses the flow and about how the app works.

**Comment by nitinrgupta** [comment]
@pelsasser We can have a separate section dedicated for OSS at the bottom below the CTA. 
Here's a quick mock of what I'm talking about 
<img width="641" alt="screen shot 2018-05-07 at 6 27 46 pm" src="https://user-images.githubusercontent.com/4952395/39703059-7c1c028c-5224-11e8-99cd-93df5906c0d1.png">

**Comment by pelsasser** [comment]
@nitinrgupta - I like this, but worry out main page may start to get long (if we end up adding more section in the future, perhaps regarding our token, etc).

Any ideas on breaking this out into a separate page?  We also will be adding a Partners page in the near future.

**Comment by nitinrgupta** [comment]
That's a good point you bought there @pelsasser. 
But, I don't see the need for an entire page dedicated for OSS contributions since we already have that part sorted out in [https://docs.marketprotocol.io/#contributing](https://docs.marketprotocol.io/#contributing)

Also, this is a small section which wouldn't consume much of a scroll space is what I feel. Well it should be fine atleast till we start adding out more sections in the future. We can also add this section in other pages along with the CTA (the join our newsletter and become a partner) section.

**Comment by pelsasser** [comment]
@nitinrgupta - okay cool.  Get Started would link to the https://docs.marketprotocol.io/#contributing I assume.

**Comment by nitinrgupta** [comment]
Yup.

Another idea which I could think of is having a small "badge" kind of thing in the footer. But this would hide the emphasis on OSS contributions and the welcoming nature of it.

**Comment by pelsasser** [comment]
agreed.

**Comment by pelsasser** [comment]
@nitinrgupta - I am closing this and passed along your design to aure to incorporate into the new "About" page that will have more info on the protocol, timeline, OSS contributions, etc.  Thanks for the mock up!
