### ISSUE TITLE
[NavBar] Add dropdown under white paper to allow for selection of white paper language.

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#46]
### User Story

Our white paper has been translated into chinese!  We need a way for people to be able to find it.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: We eventually will have many languages supported as we expand globally.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Whitepaper link in header 

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: We need a way of supporting multiple white paper versions in different languages as we have them translated. 

maybe there is a better way then a dropdown menu, but currently that seems the easiest path forward for now.  I am also not sure how this would look on the mobile site. 

## Before you `start work`
If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

**Comment by brentoneill** [comment]
@pelsasser I can take this one today after my other PR is approved

**Comment by pelsasser** [comment]
I just uploaded the WP 
https://github.com/MARKETProtocol/website/blob/develop/assets/MARKET_Protocol-Whitepaper-Chinese.pdf
