### ISSUE TITLE
[UI] Add padding to handle the UI for larger screens

### ISSUE THREAD

**Issue by cryptomental** [MARKETProtocol/website#53]
As discussed on Discord, padding should be applied to accomodate the UI for large screens. Currently the SVGs seem to be a bit too big on large monitors.

**Comment by pelsasser** [comment]
@nitinrgupta is going to take a crack at this sometime soon

**Comment by pelsasser** [comment]
@nitinrgupta - just wanted to make sure your planning on getting to this over the weekend still.  Please LMK if not

**Comment by nitinrgupta** [comment]
yes @pelsasser I'm on it. 

@cryptomental can you share some screenshots of what you meant by the illustrations being too large on big screen devices? That'd help me in visualizing how to tackle.

**Comment by pelsasser** [comment]
![image](https://user-images.githubusercontent.com/15096737/40176042-3581e11e-5997-11e8-9d9b-41590d91c8af.png)

![image](https://user-images.githubusercontent.com/15096737/40176068-490df510-5997-11e8-8e0e-06ee4b983ec7.png)

perhaps these will help @nitinrgupta

**Comment by pelsasser** [comment]
@nitinrgupta - just took a look at this, I think it looks way better!  @cryptomental curious your thoughts before we merge it.
