### ISSUE TITLE
[Press] Setup press page similar to blog

### ISSUE THREAD

**Issue by lakikentaki** [MARKETProtocol/website#93]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story

As a website visitor, I want to be updated to the latest press releases and news mentioning MARKET Protocol.

### Why Is this Needed?

*Summary*: As it currently stands, all media press releases, interviews with co-founders and third-party announcements as well as associated medium graphics and hyperlinks are posted to the [website press page](https://marketprotocol.io/press) manually. We would like to automate that process in the future, or make it so a link could be pasted by website admin, and that would pull the best graphic and caption for the mentioned publication (similarly to how posting on Facebook or Twitter works).

### Description
*Type*: Feature

### Current Behavior
Press page is updated manually

### Expected Behavior
Press page is updated automatically and publications can also be manually added/deleted via Netlify CMS. Refer to `blog` for the setup.

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: The solution would in perfect conditions be having a page as it is right now, but with no or very little manual input. The biggest issue would be pulling the right captions and publication logo that is transparent or has a darker background in order to blend with our website background RBG.

### Definition of Done
- [ ] Setup `/press` page on Netlify CMS similar to `/blog`

### Additional Information
For another good example of how the page should look like, please visit the [Bluzelle press page.](https://bluzelle.com/latest-news/press/)

**Comment by pelsasser** [comment]
@lakikentaki thanks for submitting this issue! Certainly part of the large goal and milestone of creating a content management system (CMS) that can be used by team members to add press, blogs, and newsletters to the site.

**Comment by eswarasai** [comment]
@KennethAshley -- Let us know the status on this one. Thanks!

**Comment by KennethAshley** [comment]
@eswarasai Working on it now! Do we have the posts will also be markdown right?

**Comment by eswarasai** [comment]
Yep. That's correct. So there'd be a bit of initial migration work to convert the posts to markdown.

**Comment by rojosnow** [comment]
@eswarasai Let's get an estimate on this issue, thanks!
