### ISSUE TITLE
[SEO] Update images to help with SEO 

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#94]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story

SEO is important, and I want to be able to find MARKET Protocol's site!

### Why Is this Needed?

*Summary*: Descriptive text in img alt attributes and meaningful image filenames can help us improve our search rankings.

The 'alt' attributes in <img> tags are an opportunity to use descriptive text not only for accessibility but also to provide indexable content.

Meaningful image asset/file names can also improve indexing.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

Currently, the 'alt' attributes of our images are very generic and reused. For example, many of the images simply use the alt text 'exchange'.

Currently, the svg files containing the image assets contain very generic and meaningless names such as "asset_2.svg".

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

Using 'asset_2.svg' as an example. The image depicts a smart contract representing physical or virtual assets.

A better alt attribute for the image might be "trustless and decentralized smart contract".
A better name for the image file might be 'smart-contract.svg'.

In each case, the alt text should be a concise description (a single sentence or phrase describing what is depicted) and the image name just a word, or a few words concatenated, to describe the contents.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] update all img alt attributes with descriptive key words that help MARKET Protocol SEO
- [ ] rename image assets and corresponding references in the site

**Comment by pelsasser** [comment]
@pcuck can you help us to understand what these tags should target so we can get this completed.

**Comment by pchuck** [comment]
(renamed the issue and added descriptions of how both the image names and alt attributes can be improved)

**Comment by pelsasser** [comment]
@pchuck - thanks.  I am worried that if I stake this without providing those descriptions it may be hard for an outsider to do them well.  I think I will create the descriptions before posting a bounty.

**Comment by pelsasser** [comment]
Dapp.tsx:              <img alt="baseToken" src={asset3} />
Dapp.tsx:              <img alt="baseToken" src={asset9} />
Dapp.tsx:              <img alt="baseToken" src={asset5} />
Dapp.tsx:            <img alt="tablet" src={tablet} width="100%" />
Footer.tsx:              <img alt="hero" src={logoImg} />
Footer.tsx:                    <img alt="telegram" src={telegram} width="80%" />
Footer.tsx:                    <img alt="twitter" src={twitter} width="80%" />
Footer.tsx:                    <img alt="medium" src={medium} width="80%" />
Footer.tsx:                    <img alt="github" src={github} width="80%" />
Hero.tsx:              <img alt="hero" src={heroIllustration} />
Navbar.tsx:              <img alt="react-static" width="100%" src={logoImg} />
Solution.tsx:              <img alt="exchange" src={asset1} />
Solution.tsx:              <img alt="exchange" src={asset2} />
