### ISSUE TITLE
[Press] Upload Coin Crunch Podcast with Seth Rubin on website press page!

### ISSUE THREAD

**Issue by lakikentaki** [MARKETProtocol/website#95]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Our co-founder Seth Rubin was featured in the latest Coin Crunch podcast and we would like it to be available to our website press page visitors. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

Podcast and associated captions aren't available on our website press page. 

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

Podcast and associated captions are available on our website press page. 

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: We want the podcast posted with associated captions available in the [podcast description](https://coincrunch.io/marketprotocol/), with the transparent logo of the PR publication. Logo is attached below. 

- [ ] Follow the same design style as on our current [press page](https://marketprotocol.io/press/) and consult our [branding guidelines](https://github.com/MARKETProtocol/assets/blob/master/Branding/MARKET_Protocol-Style-Guide.pdf)
- [ ] Keep the same ratio between logo and captions as previous press page content

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Podcast is posted and the hyperlink to it is attached to the publication logo and the "read more" button
- [ ] Captions are copied from the podcast description in length that matches the proportion of other press page content that was previously posted

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

Press release link: https://coincrunch.io/marketprotocol/
Publisher's logo:
![coin-crunch-2](https://user-images.githubusercontent.com/39289842/40428251-726801b2-5e65-11e8-9b23-9720987959c0.png)

**Comment by pelsasser** [comment]
Thanks @lakikentaki !!

**Comment by pelsasser** [comment]
@arun1595 that sounds great! thanks.  LMK if you need anything more.

**Comment by arun1595** [comment]
@pelsasser Sure, will do.
