### ISSUE TITLE
[SEO] Optimize .pdf whitepaper and summary for SEO

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/website#97]
@pchuck to build out issue 

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by pelsasser** [comment]
@pchuck - any chance you can shed some light on this one so we can get it moved along?

**Comment by pchuck** [comment]
* set the title attribute in the PDF (usu. under 'Document Properties' when editing the document). This is an opportunity to provide not only the precise "MARKET Protocol Whitepaper" title, but also a subtitle that targets a few key terms.

* Link to the MARKET Protocol main site when mentioned in the opening paragraph. Could also use a few additional key links, sparingly, such as to the dApp and protocol in github. Currently, the document only links to a few sources in footnotes and bios.

* if feasible, use image meta tags in the PDF (see https://www.w3.org/TR/WCAG20-TECHS/PDF1.html)

* If not feasible, consider replacing the opening page with an image and text. The title, date of the document and the subtitle "Powering safe, solvent and trustless trading of any asset" is an image and not indexed/searchable.

@pelsasser ^

**Comment by pchuck** [comment]
Found a few additional recommendations here: https://moz.com/ugc/how-to-optimize-pdf-documents-for-search

* set the 'Author' field in the PDF attributes to "MARKET Protocol"
* fill out all available document attributes (e.g. view "Additional Metadata" if authoring in Acrobat)
* write-protect the document
* make available an HTML version of the document on the marketprotocol.io site

**Comment by pelsasser** [comment]
- [x] set the title attribute in the PDF (usu. under 'Document Properties' when editing the document). This is an opportunity to provide not only the precise "MARKET Protocol Whitepaper" title, but also a subtitle that targets a few key terms.
- [x] Link to the MARKET Protocol main site when mentioned in the opening paragraph. 
- [ ] Could also use a few additional key links, sparingly, such as to the dApp and protocol in github. Currently, the document only links to a few sources in footnotes and bios.
- [ ] if feasible, use image meta tags in the PDF (see https://www.w3.org/TR/WCAG20-TECHS/PDF1.html)

- [ ] If not feasible, consider replacing the opening page with an image and text. The title, date of the document and the subtitle "Powering safe, solvent and trustless trading of any asset" is an image and not indexed/searchable.
- [x] set the 'Author' field in the PDF attributes to "MARKET Protocol"
- [x] populate the 'Keyword' field in the PDF attributes to a few concise keywords (same as #60, but perhaps refined to key topics detailed in the whitepaper itself)
- [x] fill out all available document attributes (e.g. view "Additional Metadata" if authoring in Acrobat)
- [x] write-protect the document
- [ ] make available an HTML version of the document on the marketprotocol.io site

**Comment by pelsasser** [comment]
@pchuck these changes just got deployed to prod - will keep the others in mind.
